version: '3'
services:
  api:
    build: .
    container_name: test-result-reporter-api
    image: test-result-reporter-api
    ports:
    - "8080:8080"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
  db:
    image: "postgres:11.1-alpine"
    container_name: reporter-postgres-db
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    ports:
    - "5432:5432"